language: c
env:
  # Test that funarith installs correctly without its test dependencies
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.03.0+flambda
  - OCAML_VERSION=4.04.2
  - OCAML_VERSION=4.04.2+flambda
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.05.0+flambda
  - OCAML_VERSION=4.06.0
  - OCAML_VERSION=4.06.0+flambda
addons:
  apt:
    sources:
      - avsm
    packages:
      - opam
# Caching may take a lot of space with so many ocaml versions
#cache:
#  directories:
#    - $HOME/.opam
before_install:
  # Some opam boilerplate
  - export OPAMYES=1
  - export OPAMVERBOSE=1
  - opam init
  - opam switch ${OCAML_VERSION}
  - eval `opam config env`
install:
  # Install dependencies
  - opam pin add --no-action funarith .
  - opam install --deps-only -t funarith
script:
  - make build
  - make test
