language: c
env:
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.03.0+flambda
  - OCAML_VERSION=4.04.2
  - OCAML_VERSION=4.04.2+flambda
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.05.0+flambda
  - OCAML_VERSION=4.06.0
  - OCAML_VERSION=4.06.0+flambda
addons:
  apt:
    sources:
      - avsm
    packages:
      - opam
# Caching may take a lot of space with so many ocaml versions
#cache:
#  directories:
#    - $HOME/.opam
before_install:
  - export OPAMYES=1
  - export OPAMVERBOSE=1
  - opam init
  - opam switch ${OCAML_VERSION}
  - eval `opam config env`
  - opam pin add --no-action funarith .
install:
  - opam install --with-test --deps-only funarith
script:
  - opam install --with-test funarith
