language: c
env:
  # Test that funarith installs correctly without its test dependencies
  - TEST=false OCAML_VERSION=4.03.0
  # Test installation through opam, with the TEST variable
  # set to true so that opam runs the tests
  - TEST=true OCAML_VERSION=4.03.0
  - TEST=true OCAML_VERSION=4.03.0+flambda
  - TEST=true OCAML_VERSION=4.04.2
  - TEST=true OCAML_VERSION=4.04.2+flambda
  - TEST=true OCAML_VERSION=4.05.0
  - TEST=true OCAML_VERSION=4.05.0+flambda
  - TEST=true OCAML_VERSION=4.06.0
  - TEST=true OCAML_VERSION=4.06.0+flambda
addons:
  apt:
    sources:
      - avsm
    packages:
      - opam
# Caching may take a lot of space with so many ocaml versions
#cache:
#  directories:
#    - $HOME/.opam
before_install:
  - export OPAMYES=1
  - export OPAMVERBOSE=1
  - opam init
  - opam switch ${OCAML_VERSION}
  - eval `opam config env`
  - opam pin add --no-action funarith .
install:
  - if [ "$TEST" = "false" ]; then opam install --deps-only funarith; fi
  - if [ "$TEST" = "true" ]; then opam install -t --deps-only funarith; fi
script:
  - if [ "$TEST" = "false" ]; then opam install funarith; fi
  - if [ "$TEST" = "true" ]; then opam install -t funarith; fi
